---

# Task 1: Familiarize Yourself with the Dataset

There are two main subtasks:  
1. Load the four data files that are part of this dataset.  
2. Explore each dataset and define the data types of each column. Describe the contents of each column, including the nature of the data values. Follow a similar approach as demonstrated in the lecture and tutorial. Discuss the shape of the data, value ranges, and possible categories. Convert any data into a more appropriate format if needed.  

Add as many code and markdown cells as necessary below. Typically, you should perform one type of investigation per code cell with output, and then comment on the results in a markdown cell below it.  

After completing the analysis, write a concise summary in the **Task 1: summary report** cell at the end. The final report should succinctly summarize the main characteristics of each data file, how they relate to each other, and any notable features.

## Loading the Data

In [1]:
import pandas as pd

In [2]:
sessions_df = pd.read_csv('data/sessions.csv')
streamers_df = pd.read_csv('data/streamers.csv')
streams_df = pd.read_csv('data/streams.csv')
viewers_df = pd.read_csv('data/viewers.csv')

## Exploring the Data - sessions.csv

### Columns

In [4]:
sessions_df.head()

,session_id,viewer_id,streamer_id,stream_id,started_at,ended_at,duration_mins,chat_messages_sent,bits_cheered,followed_during,subscribed_during
0,SES000001,VWR00938,STR0055,SM00860,2024-01-18 19:16:00,2024-01-18 20:28:00,72,0,0,False,False
1,SES000002,VWR00804,STR0034,SM00542,2024-01-04 17:11:00,2024-01-04 19:41:00,150,11,0,False,False
2,SES000003,VWR00704,STR0008,SM00124,2024-02-15 15:11:00,2024-02-15 16:53:00,102,5,0,False,False
3,SES000004,VWR00926,STR0024,SM00373,2024-01-18 19:59:00,2024-01-18 20:56:00,57,3,9663,False,False
4,SES000005,VWR00883,STR0008,SM00120,2024-03-19 20:08:00,2024-03-19 20:22:00,14,7,0,False,False

- session_id appears to be a unique identifier for a session consisting of: a unique viewer, stream, streamer combination
- viewer_id appears to be an identifier for the viewer in the session
- streamer_id appears to be an identifier for the streamer the viewer's watching in the session
- stream_id appears to be an identifier for the stream that a viewer is watching in the session
- started_at appears to be a datetime for when the viewer began watching the stream (we can tell because in the dataset, different sessions for the same stream have different datetimes)
- ended_at appears to be a datetime for when the viewer finished watching the stream (same reasoning as started_at)
- duration_mins appears to be a count of the minutes the viewer watched the stream for
- chat_messages_sent appears to be a count of the chat messages sent by the viewer
- bits_cheered appears to be a count of the bits cheered by the viewer 
- followed_during appears to be a boolean checking whether the viewer followed the streamer during the session
- subscribed_during appears to be a boolean checking whether the viewer subscribed to the streamer during the session

### Data Types

In [7]:
sessions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22825 entries, 0 to 22824
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   session_id          22825 non-null  object
 1   viewer_id           22825 non-null  object
 2   streamer_id         22765 non-null  object
 3   stream_id           22825 non-null  object
 4   started_at          22825 non-null  object
 5   ended_at            22825 non-null  object
 6   duration_mins       22825 non-null  int64
 7   chat_messages_sent  22825 non-null  int64
 8   bits_cheered        22825 non-null  int64
 9   followed_during     22825 non-null  bool
 10  subscribed_during   22825 non-null  bool
dtypes: bool(2), int64(3), object(6)
memory usage: 1.6+ MB

- int64 is used for duration_mins. chat_messages_sent, and bits_cheered. This is fine, as they're counts. 
- bool is used for followed_during and subscribed_during. This is also fine, as they're simple checks. 
- We can see that many of the columns are using the dtype 'object'. In pandas, this is a catch-all dtype. It's usually used for strings, as it is for session_id, viewer_id, and streamer_id. It is fine for these, as they're string identifiers. 
  - However, 'object' dtype is also being used for started_at and ended_at columns. These are datetimes. They should be using datetime dtype, otherwise we will be unable to do date math on them. 

Let's convert started_at and ended_at to use datetime.

In [8]:
sessions_df['started_at'] = pd.to_datetime(sessions_df['started_at'])
sessions_df['ended_at']   = pd.to_datetime(sessions_df['ended_at'])

In [9]:
sessions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22825 entries, 0 to 22824
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   session_id          22825 non-null  object
 1   viewer_id           22825 non-null  object
 2   streamer_id         22765 non-null  object
 3   stream_id           22825 non-null  object
 4   started_at          22825 non-null  datetime64[ns]
 5   ended_at            22825 non-null  datetime64[ns]
 6   duration_mins       22825 non-null  int64
 7   chat_messages_sent  22825 non-null  int64
 8   bits_cheered        22825 non-null  int64
 9   followed_during     22825 non-null  bool
 10  subscribed_during   22825 non-null  bool
dtypes: bool(2), datetime64[ns](2), int64(3), object(4)
memory usage: 1.6+ MB

Perfect!

### Shape, Ranges, and Categories

In [10]:
sessions_df.shape

(22825, 11)

In [11]:
sessions_df.describe()

,started_at,ended_at,duration_mins,chat_messages_sent,bits_cheered
count,22825,22825,22825.000000,22825.000000,22825.000000
mean,2024-02-14 07:00:46.236144896,2024-02-14 07:59:41.457174016,59.051303,6.442629,398.425323
min,2024-01-01 08:20:00,2024-01-01 08:24:00,0.000000,0.000000,0.000000
25%,2024-01-23 13:18:00,2024-01-23 14:20:00,15.000000,0.000000,0.000000
50%,2024-02-13 14:48:00,2024-02-13 15:57:00,39.000000,1.000000,0.000000
75%,2024-03-07 20:09:00,2024-03-07 21:23:00,83.000000,5.000000,0.000000
max,2024-03-31 01:22:00,2024-03-31 01:54:00,443.000000,1987.000000,10000.000000
std,NaN,NaN,60.383979,46.576309,1571.528658

A category is a column whose values come from a limited, fixed set of options rather than being free-form numbers or text. 

I believe followed_during and subscribed_during are categories for this dataset.

In [13]:
sessions_df['followed_during'].value_counts()

followed_during
False    21663
True      1162
Name: count, dtype: int64

In [14]:
sessions_df['subscribed_during'].value_counts()

subscribed_during
False    22383
True       442
Name: count, dtype: int64

The output from these makes sense. There are only True or False for both of them. Both are skewed towards false, since following and subscribing are relatively rare events.

## Exploring the Data - streamers.csv

### Columns

In [3]:
streamers_df.head()

,streamer_id,streamer_name,category,language,partner_status,total_followers,avg_concurrent_viewers
0,STR0001,xQc,Just Chatting,English,True,11500000,138706
1,STR0002,Pokimane,Just Chatting,English,True,-25551,71660
2,STR0003,HasanAbi,Just Chatting,English,True,2600000,34220
3,STR0004,Amouranth,Just Chatting,English,True,6200000,68607
4,STR0005,Mizkif,Just Chatting,English,True,2100000,6771

- streamer_id appears to be a unique identifier for a unique streamer
- streamer_name appears to be the name of the streamer
- category appears to be the activity the streamer's currently doing (or usually does? Not clear)
- language appears to be the language the streamer speaks/communicates in
- partner_status appears to be a boolean checking whether the streamer is a Twitch partner or not
- total_followers appears to be a count of the streamer's followers (at the time the data was collected)
- avg_concurrent_viewers appears to be a count of the average number of viewers in the streamer's stream at once 

NOTE that the second row of the dataset shows a negative amount of followers for Pokimane. This is likely an error that will need to be cleaned.

### Data Types

In [15]:
streamers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   streamer_id             76 non-null     object
 1   streamer_name           76 non-null     object
 2   category                76 non-null     object
 3   language                68 non-null     object
 4   partner_status          76 non-null     bool
 5   total_followers         76 non-null     int64
 6   avg_concurrent_viewers  76 non-null     int64
dtypes: bool(1), int64(2), object(4)
memory usage: 3.8+ KB

- As mentioned, object dtype is used commonly for strings. Here, it's used for streamer_id, streamer_name, category, and language. These are all fine as these are identifiers and categories, so they must be text. 
- bool is used for partner_status. This is good as it's a category with only two options. 
- int64 is used for total_followers and and avg_concurrent_viewers. This is good for both of them because we are counting people, so we'd like whole numbers.

### Shape, Ranges, and Categories

In [17]:
streamers_df.shape

(76, 7)

In [18]:
streamers_df.describe()

       total_followers  avg_concurrent_viewers
count     7.600000e+01               76.000000
mean      3.300886e+06            31227.986842
std       3.793772e+06            38307.223652
min      -4.696400e+04              634.000000
25%       7.800000e+05             6633.250000
50%       2.000000e+06            14762.500000
75%       3.875000e+06            36840.750000
max       1.870000e+07           156401.000000

Note negative total_followers as the min value. Must be cleaned.

For this dataset, the categories are category (duh!), language, and partner_status.

In [19]:
streamers_df['category'].value_counts()

category
Just Chatting    18
FPS              13
Creative         13
MOBA             12
Sports           11
IRL               9
Name: count, dtype: int64

In [20]:
streamers_df['language'].value_counts()

language
English       61
Spanish        5
Korean         1
Portuguese     1
Name: count, dtype: int64

In [21]:
streamers_df['partner_status'].value_counts()

partner_status
True     66
False    10
Name: count, dtype: int64

Looks Good!

## Exploring the Data - streams.csv

### Columns

In [5]:
streams_df.head()

,stream_id,streamer_id,started_at,ended_at,stream_duration_hrs,category,peak_viewers,title_has_hype_word,was_raid
0,SM00001,STR0001,2024-02-14 18:00:00,2024-02-14 21:00:00,3.0,Just Chatting,108989.0,False,True
1,SM00002,STR0001,2024-01-28 18:00:00,2024-01-28 21:00:00,3.0,Just Chatting,51635.0,True,False
2,SM00003,STR0001,2024-01-31 09:00:00,2024-01-31 16:00:00,7.0,Just Chatting,212127.0,False,False
3,SM00004,STR0001,2024-03-03 14:00:00,2024-03-03 21:00:00,7.0,Just Chatting,186745.0,False,True
4,SM00005,STR0001,2024-01-24 18:00:00,2024-01-24 21:00:00,3.0,Just Chatting,87723.0,False,True

- stream_id appears to be a unique identifier for a unique stream
- streamer_id appears to be the name of the streamer who is streaming
- started_at appears to be the datetime that the stream began
- ended_at appears to be the datetime that the stream ended at 
- stream_duration_hrs appears to be the length of the stream in hours (float)
- category appears to be the activity that the streamer was doing during the stream
- peak_viewers appears to be a count of the most viewers that the stream had, at once 
- title_has_hype_word appears to be a bool that checks whether the title of the stream contained a "hype word" (unclear what this is)
- was_raid appears to be a bool that checks whether the stream was "raided" by the viewers of another streamer

NOTE we had to convert datetimes from object dtype to datetime for other dataset, may have to do the same for this one

### Data Types

In [22]:
streams_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1199 entries, 0 to 1198
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   stream_id            1199 non-null   object
 1   streamer_id          1199 non-null   object
 2   started_at           1199 non-null   object
 3   ended_at             1199 non-null   object
 4   stream_duration_hrs  1199 non-null   float64
 5   category             1149 non-null   object
 6   peak_viewers         1119 non-null   float64
 7   title_has_hype_word  1199 non-null   bool
 8   was_raid             1199 non-null   bool
dtypes: bool(2), float64(2), object(5)
memory usage: 68.0+ KB

- object dtype is used for stream_id, streamer_id, started_at, ended_at, and category. Most are fine as these are identifiers and categories, so they must be text. 
  - However, as before, we must convert started_at and ended_at to datetime dtype in order to be able to do math with them later
- bool is used for title_has_hype_word and was_raid. This is good as they're categories with only two options. 
- float64 is used for stream_duration_hrs and and peak_viewers. This is good for stream_duration_hrs because the duration of the stream may not be in a whole number. 
  - peak_viewers probably shouldn't be a float, since we're counting people. This potentially points to a data issue. We'll investigate later, but leave it for now.

In [23]:
# convert started_at and ended_at to datetime
streams_df['started_at'] = pd.to_datetime(streams_df['started_at'])
streams_df['ended_at']   = pd.to_datetime(streams_df['ended_at'])

In [24]:
streams_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1199 entries, 0 to 1198
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   stream_id            1199 non-null   object
 1   streamer_id          1199 non-null   object
 2   started_at           1199 non-null   datetime64[ns]
 3   ended_at             1199 non-null   datetime64[ns]
 4   stream_duration_hrs  1199 non-null   float64
 5   category             1149 non-null   object
 6   peak_viewers         1119 non-null   float64
 7   title_has_hype_word  1199 non-null   bool
 8   was_raid             1199 non-null   bool
dtypes: bool(2), datetime64[ns](2), float64(2), object(3)
memory usage: 68.0+ KB

Perfect!

### Shape, Ranges, and Categories

In [25]:
streams_df.shape

(1199, 9)

In [26]:
streams_df.describe()

,started_at,ended_at,stream_duration_hrs,peak_viewers
count,1199,1199,1199.000000,1119.000000
mean,2024-02-14 08:18:33.928273408,2024-02-14 12:05:27.272727296,4.625104,38375.658624
min,2024-01-01 08:00:00,2024-01-01 10:30:00,1.500000,-50.000000
25%,2024-01-23 18:30:00,2024-01-23 22:30:00,2.500000,7598.500000
50%,2024-02-13 17:00:00,2024-02-13 21:00:00,3.000000,20224.000000
75%,2024-03-07 15:30:00,2024-03-07 20:00:00,5.000000,47941.000000
max,2024-03-30 21:00:00,2024-03-31 02:00:00,96.000000,370165.000000
std,NaN,NaN,7.995028,50377.085406

Note negative min peak_viewers. Must be cleaned.

For this dataset, the categories are category (duh!), title_has_hype_word, and was_raid

In [27]:
streams_df['category'].value_counts()

category
Just Chatting    275
FPS              208
Creative         191
Sports           178
MOBA             170
IRL              127
Name: count, dtype: int64

In [28]:
streams_df['title_has_hype_word'].value_counts()

title_has_hype_word
False    853
True     346
Name: count, dtype: int64

In [29]:
streams_df['was_raid'].value_counts()

was_raid
False    1032
True      167
Name: count, dtype: int64

Looks Right!

## Exploring the Data - viewers.csv

### Columns

In [30]:
viewers_df.head()

,viewer_id,age_group,country,account_age_days,subscription_tier,preferred_category
0,VWR00001,18-24,AR,355,free,IRL
1,VWR00002,25-34,CA,1670,free,Creative
2,VWR00003,35-44,US,1108,free,Just Chatting
3,VWR00004,45+,NaN,822,tier1,FPS
4,VWR00005,25-34,DE,2226,free,Just Chatting

- viewer_id appears to be a unique identifier for a unique viewer
- age-group appears to be a the age category that the viewer belongs to 
- country appears to be the country the viewer belongs to 
- account_age_days appears to be the age of the viewer's account, in days
- subscription tier appears to be the subscription tier of the viewer's account 
- preferred_category appears to be the category that the viewer likes to watch most often

### Data Types

In [31]:
viewers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   viewer_id           1000 non-null   object
 1   age_group           1000 non-null   object
 2   country             920 non-null    object
 3   account_age_days    1000 non-null   int64
 4   subscription_tier   1000 non-null   object
 5   preferred_category  1000 non-null   object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

- object dtype is used for viewer_id, age_group, country, subscription_tier, and preferred_category. These are fine as these are identifiers and categories, so they must be text. 
- int64 is used for account_age_days. This is good because we are counting days, so we'd like whole numbers.

### Shape, Ranges, and Categories

In [32]:
viewers_df.shape

(1000, 6)

In [33]:
viewers_df.describe()

       account_age_days
count       1000.000000
mean        1881.119000
std         1036.144656
min           33.000000
25%          984.500000
50%         1966.500000
75%         2761.250000
max         3645.000000

For this dataset, the categories are age_group, country, subscription_tier, and preferred_category.

In [34]:
viewers_df['age_group'].value_counts()

age_group
18-24       334
25-34       289
35-44       134
45+         111
13-17        95
18–24        11
18 to 24     11
25–34         6
35 to 44      4
25 to 34      3
35–44         2
Name: count, dtype: int64

This is concerning. There are multiple categories for what should be the same. We'll address this in cleaning.

In [35]:
viewers_df['country'].value_counts()

country
US       264
GB        82
CA        66
DE        53
BR        51
FR        47
KR        44
MX        40
other     38
JP        33
AU        31
IT        28
NL        22
ES        21
RU        20
AR        19
SE        19
IN        18
PL        17
TR         7
Name: count, dtype: int64

Looks ok.

In [36]:
viewers_df['subscription_tier'].value_counts()

subscription_tier
free          578
tier1         243
tier2         100
tier3          49
premium        10
none            7
TIER1           5
free trial      4
tier4           4
Name: count, dtype: int64

Again, concerning. Multiple tier 1s. Will need to address in cleaning.

In [37]:
viewers_df['preferred_category'].value_counts()

preferred_category
Just Chatting    269
FPS              230
MOBA             161
IRL              120
Creative         117
Sports           103
Name: count, dtype: int64

Looks fine.

## Task 1 Summary Report

After completing the analysis, write a concise summary in the **Task 1: summary report** cell at the end. The final report should succinctly summarize the main characteristics of each data file, how they relate to each other, and any notable features.

# Task 2: Data Cleaning, Diagnostics, and Corrections

Identify and resolve issues in the dataset. These can be of different kinds, such as:
- Look for duplicates or implausible values (e.g., users with negative followers, invalid age groups). Thoroughly document your exploration of the data. Decide whether these are outliers or the result of a systemic problem. If the latter, resolve the problem here; if they are outliers, we will address those later.  
- Define at least three heuristics (common-sense rules) to flag unusual entries (e.g., someone watching dozens of streams per day). Discuss whether what you found are errors or artifacts.  

I will repeat the instructions here, but this is expected for each task: each code cell should focus on a specific analysis. You should run the code, and in the markdown below each code cell and its result, provide a detailed interpretation of what you have uncovered in that step. After completing the analyses, summarize the key findings in the indicated summary report cell below.

In [ ]:
# start code for Task 2 here

### Task 2 summary report

# Task 3: Descriptive Statistics and Visualizations

- Create summary statistics and visualizations to understand user characteristics  
- Create summary statistics for streams data overall, and summaries by age group, account tire, or peak viewers  
- Visualize the distribution of streams durations, popular categories,   
- Show category-specific information and compare streamers based on categories

In [ ]:
#start code for Task 3 here

### Task 3 Summary report
summarize your findings here.

# Task 4: Dealing with Outliers and Missing Values

- Are there any missing values or outliers in the original data? Perform the analysis and report your findings.  
- Are there any outliers or missing values in the derived data? Perform the analysis and report your findings.  
- If there are no outliers or missing values, introduce 3–5% of missing values in a selected column and 1–2% of outliers in another column.  
- Experiment with two strategies for imputing missing values and two strategies for handling outliers. Show how each strategy affects the characteristics of the data.

In [ ]:
#start code for Task 4 here

### Task 4 Summary report

# Task 5: Correlation and Behavioral Patterns

- Compute pairwise correlations between user features and the number of check-ins  
- Visualize the results using a correlation matrix (use a coolwarm color scheme and proper scaling)  
- Try Spearman rank correlation and explain when it is more appropriate than Pearson

In [ ]:
# tast 5 code starts here

### Task 5 Summary report

# Task 6: Compare Behavior Across User Segments

- Segment users into 2–3 groups (e.g., by age bracket, account tire)  
- Compare their viewing behavior over time using boxplots or dot plots  
- Identify any outliers in group behavior and investigate them

In [ ]:
# task 6 code start here

### Task 6 Summary report

# Task 7: Your Own EDA Questions

Formulate and explore two hypotheses of your own:  
- Propose questions based on curiosity (e.g., “Does a user's variety of categories influence morning vs. evening or session duration?”)  
- Use summary statistics and visualizations to answer each question  
- Briefly discuss what additional data would help you answer the questions more effectively

In [ ]:
# task 7 code start here

### Task 7 Summary report

# Task 8: EDA Presentation (Insight Report)

Summarize your findings in a polished format:  
- Create 3–4 slides or a single-page report highlighting your most important insights  
- Include at least 2 charts and interpret them using clear, plain language  
- Apply Tufte’s principles: minimize chartjunk, maximize data-to-ink ratio, and ensure clear labeling